import struct

PROTOCOL_ID = b"MLSP"
VERSION = 1
MSG_DATA = 1
MSG_EVENT = 2
MSG_INIT = 3
HEADER_FMT = "!4sBBIIQHI"
HEADER_SIZE = struct.calcsize(HEADER_FMT)

GRID_SIZE = 5
CELL_SIZE = 65

BROADCAST_FREQUENCY = 0.05 # 50ms